// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzV5MEDjB3zDB_a0eDYYZVohH18RMlf80',
    appId: '1:917534241010:web:3a90d70ee7b6d18974206b',
    messagingSenderId: '917534241010',
    projectId: 'flutter-praktika',
    authDomain: 'flutter-praktika.firebaseapp.com',
    storageBucket: 'flutter-praktika.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbeFX8MycOafHN3kmOU8VvZBinU03WIY',
    appId: '1:917534241010:android:76eb2dc53650e29974206b',
    messagingSenderId: '917534241010',
    projectId: 'flutter-praktika',
    storageBucket: 'flutter-praktika.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzUrrz4l3Lbvcv0P1TpWktbJ7XkFqmiA',
    appId: '1:917534241010:ios:06f8f91a0fb83fb074206b',
    messagingSenderId: '917534241010',
    projectId: 'flutter-praktika',
    storageBucket: 'flutter-praktika.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzUrrz4l3Lbvcv0P1TpWktbJ7XkFqmiA',
    appId: '1:917534241010:ios:20c82d88b13c3c9b74206b',
    messagingSenderId: '917534241010',
    projectId: 'flutter-praktika',
    storageBucket: 'flutter-praktika.appspot.com',
    iosBundleId: 'com.example.flutterPractice.RunnerTests',
  );
}
